### ISSUE TITLE
In Arrays 

### ISSUE THREAD

**Issue by PhilippeZeitoun** [ardanlabs/gotour#245]
**Declaring and Initializing Values**

it is written "This means that each string has the first word set to nil and the second word set to 0."
But, this shouldn't be "This means that each string has the first word set to nil and the second word set to an empty string ("")." ?

**Comment by alexandear** [comment]
Not really. Let's review the whole paragraph from the https://tour.ardanlabs.com/tour/eng/arrays/1:

> A string is an immutable, two word, data structure representing a pointer to a
backing array of bytes and the total number of bytes in the backing array. Since
this array is set to its zero value state, every element is set to its zero value
state. This means that each string has the first word set to nil and the second
word set to 0.

A string is **two word** data structure. First word - a pointer to a backing array, second word - the total number of bytes. So, "the second word set to 0" is correct, because it's the number of bytes.
